### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by gaozhangmin** [intfloat/word-sense-induction#1]
你好，试跑你的程序特征提取部分的时候有bug,
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at edu.pku.wsi.ins.WSIDocument.toString(WSIDocument.java:47)
	at java.lang.String.valueOf(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at edu.pku.wsi.ins.WSIDataset.dumpToFile(WSIDataset.java:50)
	at edu.pku.wsi.feat.FeatureExtractor.main(FeatureExtractor.java:33)

**Comment by intfloat** [comment]
谢谢你指出这个问题

src/edu/pku/wsi/util/XMLUtils.java： 70
```java
assert document.setSentenceGoldLabel(id, clusterID);
````
不加命令行参数-ea不会执行后面的函数，我一开始没注意到这一点。

bug已经通过这个补丁修复：https://github.com/intfloat/word-sense-induction/commit/b6295e0b5e9c2b9eba17a97fc99e55baad1be7f7

谢谢~
